/* C++ code produced by gperf version 3.1 */
/* Command-line: gperf -I -L C++ gperf_data_1000.txt  */
/* Computed positions: -k'1-5,8,10,$' */

#if !((' ' == 32) && ('!' == 33) && ('"' == 34) && ('#' == 35) \
      && ('%' == 37) && ('&' == 38) && ('\'' == 39) && ('(' == 40) \
      && (')' == 41) && ('*' == 42) && ('+' == 43) && (',' == 44) \
      && ('-' == 45) && ('.' == 46) && ('/' == 47) && ('0' == 48) \
      && ('1' == 49) && ('2' == 50) && ('3' == 51) && ('4' == 52) \
      && ('5' == 53) && ('6' == 54) && ('7' == 55) && ('8' == 56) \
      && ('9' == 57) && (':' == 58) && (';' == 59) && ('<' == 60) \
      && ('=' == 61) && ('>' == 62) && ('?' == 63) && ('A' == 65) \
      && ('B' == 66) && ('C' == 67) && ('D' == 68) && ('E' == 69) \
      && ('F' == 70) && ('G' == 71) && ('H' == 72) && ('I' == 73) \
      && ('J' == 74) && ('K' == 75) && ('L' == 76) && ('M' == 77) \
      && ('N' == 78) && ('O' == 79) && ('P' == 80) && ('Q' == 81) \
      && ('R' == 82) && ('S' == 83) && ('T' == 84) && ('U' == 85) \
      && ('V' == 86) && ('W' == 87) && ('X' == 88) && ('Y' == 89) \
      && ('Z' == 90) && ('[' == 91) && ('\\' == 92) && (']' == 93) \
      && ('^' == 94) && ('_' == 95) && ('a' == 97) && ('b' == 98) \
      && ('c' == 99) && ('d' == 100) && ('e' == 101) && ('f' == 102) \
      && ('g' == 103) && ('h' == 104) && ('i' == 105) && ('j' == 106) \
      && ('k' == 107) && ('l' == 108) && ('m' == 109) && ('n' == 110) \
      && ('o' == 111) && ('p' == 112) && ('q' == 113) && ('r' == 114) \
      && ('s' == 115) && ('t' == 116) && ('u' == 117) && ('v' == 118) \
      && ('w' == 119) && ('x' == 120) && ('y' == 121) && ('z' == 122) \
      && ('{' == 123) && ('|' == 124) && ('}' == 125) && ('~' == 126))
/* The character set is not based on ISO-646.  */
#error "gperf generated tables don't work with this execution character set. Please report a bug to <bug-gperf@gnu.org>."
#endif

#include <string.h>

#define TOTAL_KEYWORDS 1000
#define MIN_WORD_LENGTH 2
#define MAX_WORD_LENGTH 31
#define MIN_HASH_VALUE 19
#define MAX_HASH_VALUE 5631
/* maximum key range = 5613, duplicates = 0 */

class Perfect_Hash
{
private:
  static inline unsigned int hash (const char *str, size_t len);
public:
  static const char *in_word_set (const char *str, size_t len);
};

inline unsigned int
Perfect_Hash::hash (const char *str, size_t len)
{
  static unsigned short asso_values[] =
    {
      5632, 5632, 5632, 5632, 5632, 5632, 5632, 5632, 5632, 5632,
      5632, 5632, 5632, 5632, 5632, 5632, 5632, 5632, 5632, 5632,
      5632, 5632, 5632, 5632, 5632, 5632, 5632, 5632, 5632, 5632,
      5632, 5632, 5632, 5632, 5632, 5632, 5632, 5632, 5632, 5632,
      5632, 5632, 5632, 5632, 5632, 5632, 5632, 5632, 5632, 5632,
         0,   25,    0,    5,   20, 5632,   15, 5632, 5632, 5632,
      5632, 5632, 5632, 5632, 5632,  285,   80,  231,  200,   95,
       115,  155,  570,  290,   85,  125,  235,  330,  750,  205,
        10,   80,  341,  520,  390,  475,   45,   95,   10,   60,
        90, 5632, 5632, 5632, 5632, 5632, 5632,  872,  835,   30,
         5,   60,   15,  570,  305,  220, 1864, 1005,   80, 1444,
       270,  105,   20,  610,    0,   40,   10,   50,  205,  615,
      2058,  585,  103,  170,   15,    0, 5632, 5632, 5632, 5632,
      5632, 5632, 5632, 5632, 5632, 5632, 5632, 5632, 5632, 5632,
      5632, 5632, 5632, 5632, 5632, 5632, 5632, 5632, 5632, 5632,
      5632, 5632, 5632, 5632, 5632, 5632, 5632, 5632, 5632, 5632,
      5632, 5632, 5632, 5632, 5632, 5632, 5632, 5632, 5632, 5632,
      5632, 5632, 5632, 5632, 5632, 5632, 5632, 5632, 5632, 5632,
      5632, 5632, 5632, 5632, 5632, 5632, 5632, 5632, 5632, 5632,
      5632, 5632, 5632, 5632, 5632, 5632, 5632, 5632, 5632, 5632,
      5632, 5632, 5632, 5632, 5632, 5632, 5632, 5632, 5632, 5632,
      5632, 5632, 5632, 5632, 5632, 5632, 5632, 5632, 5632, 5632,
      5632, 5632, 5632, 5632, 5632, 5632, 5632, 5632, 5632, 5632,
      5632, 5632, 5632, 5632, 5632, 5632, 5632, 5632, 5632, 5632,
      5632, 5632, 5632, 5632, 5632, 5632, 5632, 5632, 5632, 5632,
      5632, 5632, 5632, 5632, 5632, 5632, 5632, 5632, 5632
    };
  unsigned int hval = len;

  switch (hval)
    {
      default:
        hval += asso_values[static_cast<unsigned char>(str[9])];
      /*FALLTHROUGH*/
      case 9:
      case 8:
        hval += asso_values[static_cast<unsigned char>(str[7])];
      /*FALLTHROUGH*/
      case 7:
      case 6:
      case 5:
        hval += asso_values[static_cast<unsigned char>(str[4]+1)];
      /*FALLTHROUGH*/
      case 4:
        hval += asso_values[static_cast<unsigned char>(str[3])];
      /*FALLTHROUGH*/
      case 3:
        hval += asso_values[static_cast<unsigned char>(str[2]+2)];
      /*FALLTHROUGH*/
      case 2:
        hval += asso_values[static_cast<unsigned char>(str[1]+3)];
      /*FALLTHROUGH*/
      case 1:
        hval += asso_values[static_cast<unsigned char>(str[0])];
        break;
    }
  return hval + asso_values[static_cast<unsigned char>(str[len - 1])];
}

const char *
Perfect_Hash::in_word_set (const char *str, size_t len)
{
  static const char * wordlist[] =
    {
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "",
      "rarr",
      "", "", "", "",
      "darr",
      "", "", "", "", "", "", "", "",
      "top",
      "", "", "", "",
      "par",
      "dopf",
      "", "", "", "",
      "Popf",
      "", "", "", "",
      "fopf",
      "", "", "", "",
      "popf",
      "", "", "",
      "cap",
      "", "", "", "", "",
      "copf",
      "", "", "", "",
      "uarr",
      "", "",
      "pr",
      "",
      "sopf",
      "",
      "capdot",
      "", "",
      "Vopf",
      "", "", "", "",
      "uopf",
      "", "", "", "", "", "", "",
      "rarrbfs",
      "",
      "eopf",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "",
      "lap",
      "", "", "", "", "",
      "spar",
      "", "", "", "",
      "caps",
      "", "", "", "", "",
      "rrarr",
      "", "", "",
      "Eopf",
      "",
      "frac12",
      "", "",
      "tint",
      "",
      "frac15",
      "zopf",
      "",
      "oopf",
      "",
      "frac45",
      "", "",
      "prap",
      "",
      "easter",
      "", "",
      "Fopf",
      "ccaps",
      "rarrtl",
      "", "",
      "lpar",
      "loarr",
      "emsp14",
      "", "", "", "",
      "frac25",
      "",
      "fpartint",
      "dHar",
      "",
      "frac58",
      "", "", "",
      "caret",
      "",
      "larrbfs",
      "",
      "flat",
      "trade",
      "", "",
      "ord",
      "opar",
      "rlarr",
      "emsp13",
      "", "",
      "oast",
      "erarr",
      "", "", "",
      "Gopf",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "ordf",
      "",
      "urcrop",
      "",
      "sqsubset",
      "", "", "", "", "", "",
      "lbarr",
      "dlcrop",
      "",
      "swarr",
      "dArr",
      "",
      "emptyset",
      "",
      "dot",
      "varr",
      "raquo",
      "eparsl",
      "", "", "",
      "omacr",
      "", "",
      "rfr",
      "Dopf",
      "", "", "",
      "dfr",
      "Oopf",
      "", "", "",
      "Xfr",
      "cire",
      "",
      "sqsube",
      "",
      "ffr",
      "", "", "", "",
      "pfr",
      "Larr",
      "",
      "elsdot",
      "",
      "els",
      "Cap",
      "llarr",
      "cacute",
      "", "",
      "uArr",
      "Copf",
      "", "",
      "cirfnint",
      "scnE",
      "", "", "",
      "timesbar",
      "dscr",
      "",
      "timesd",
      "",
      "smt",
      "tscr",
      "", "", "",
      "ufr",
      "fscr",
      "olarr",
      "", "", "",
      "pscr",
      "", "",
      "orderof",
      "Yfr",
      "", "", "", "",
      "doteqdot",
      "cscr",
      "Coproduct",
      "", "",
      "lat",
      "nopf",
      "", "", "",
      "scE",
      "sscr",
      "", "",
      "Pi",
      "lfr",
      "cirE",
      "", "", "",
      "Jfr",
      "dotsquare",
      "",
      "Zacute",
      "pi",
      "prE",
      "Iopf",
      "",
      "Eacute",
      "lozenge",
      "Wfr",
      "escr",
      "",
      "roplus",
      "harrcir",
      "",
      "zacute",
      "", "", "",
      "ofr",
      "hopf",
      "",
      "rcaron",
      "", "",
      "npar",
      "imacr",
      "", "",
      "Ffr",
      "Qscr",
      "",
      "tcaron",
      "", "",
      "Jscr",
      "lAarr",
      "", "",
      "Map",
      "Zscr",
      "", "", "", "",
      "Escr",
      "", "", "",
      "ulcorner",
      "", "",
      "ccaron",
      "orslope",
      "", "",
      "Ropf",
      "smashp",
      "", "",
      "perp",
      "smtes",
      "scaron",
      "", "",
      "Vert",
      "", "", "",
      "Gfr",
      "smte",
      "", "", "", "",
      "Kscr",
      "", "", "",
      "llcorner",
      "", "",
      "lsquor",
      "", "", "",
      "npart",
      "", "", "", "",
      "Amacr",
      "loplus",
      "", "", "",
      "Imacr",
      "", "",
      "Dot",
      "vArr",
      "", "", "", "",
      "Topf",
      "rsquo",
      "nrarrc",
      "ee",
      "olt",
      "sect",
      "",
      "Zcaron",
      "",
      "Dfr",
      "", "",
      "Oacute",
      "", "", "", "", "", "",
      "nis",
      "zcaron",
      "iprod",
      "", "",
      "nwarr",
      "",
      "nlarr",
      "iacute",
      "",
      "ifr",
      "excl",
      "", "", "", "", "", "", "",
      "Cacute",
      "",
      "Cfr",
      "uplus",
      "Lacute",
      "",
      "lesdotor",
      "", "", "",
      "sext",
      "",
      "Oscr",
      "eplus",
      "lesdot",
      "",
      "les",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "",
      "Uarr",
      "", "", "", "",
      "real",
      "Cscr",
      "nacute",
      "", "", "",
      "lescc",
      "", "", "",
      "lesseqgtr",
      "", "", "", "", "", "",
      "Aacute",
      "", "",
      "hArr",
      "", "",
      "ii",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "olcir",
      "drcorn",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "Cayleys",
      "", "",
      "varrho",
      "", "",
      "Sopf",
      "", "",
      "DD",
      "", "",
      "ratio",
      "", "", "", "",
      "efDot",
      "",
      "Sc",
      "nsc",
      "", "", "", "", "",
      "Rfr",
      "natur",
      "", "", "",
      "rationals",
      "", "",
      "dd",
      "",
      "upsi",
      "",
      "period",
      "", "", "", "",
      "dlcorn",
      "Conint",
      "nlt",
      "epsi",
      "", "", "",
      "gap",
      "", "", "", "", "",
      "gopf",
      "", "", "", "", "",
      "Rscr",
      "ncaron",
      "", "",
      "half",
      "", "", "", "",
      "yopf",
      "",
      "nprcue",
      "",
      "Tfr",
      "", "",
      "target",
      "",
      "nlE",
      "", "", "", "", "", "", "",
      "telrec",
      "ne",
      "", "", "",
      "DotDot",
      "", "",
      "qopf",
      "",
      "vartriangleright",
      "", "",
      "AMP",
      "",
      "nlArr",
      "", "", "", "",
      "homtht",
      "",
      "naturals",
      "nsce",
      "", "", "", "", "", "", "",
      "wr",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "Rcaron",
      "tau",
      "", "",
      "rdquor",
      "", "",
      "star",
      "",
      "expectation",
      "", "",
      "prod",
      "", "",
      "congdot",
      "", "", "",
      "daleth",
      "",
      "pre",
      "",
      "CenterDot",
      "Uacute",
      "lt",
      "", "", "",
      "rarrpl",
      "", "", "", "",
      "plankv",
      "", "", "", "", "",
      "cemptyv",
      "",
      "prop",
      "", "", "",
      "ldrushar",
      "", "",
      "Tcaron",
      "", "", "",
      "disin",
      "hearts",
      "", "", "", "", "",
      "rotimes",
      "profsurf",
      "",
      "langd",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "",
      "iff",
      "",
      "eogon",
      "ldquor",
      "", "", "",
      "rightthreetimes",
      "equest",
      "",
      "rcy",
      "", "", "", "",
      "dcy",
      "",
      "dwangle",
      "circeq",
      "Gt",
      "Pcy",
      "Nopf",
      "sqsup",
      "prurel",
      "", "", "",
      "rdquo",
      "", "",
      "pcy",
      "", "", "", "", "", "",
      "Eogon",
      "", "",
      "Hfr",
      "",
      "dtdot",
      "", "", "", "", "", "", "",
      "scy",
      "", "",
      "yacute",
      "ltquest",
      "yfr",
      "ltcc",
      "",
      "dagger",
      "lotimes",
      "ucy",
      "",
      "Tilde",
      "sqsupe",
      "",
      "EmptyVerySmallSquare",
      "", "", "", "",
      "Ycy",
      "",
      "swarrow",
      "", "", "",
      "Hscr",
      "", "", "",
      "qfr",
      "", "", "", "",
      "ETH",
      "eDot",
      "utdot",
      "", "",
      "lcy",
      "yscr",
      "",
      "vangrt",
      "", "", "", "",
      "propto",
      "Lt",
      "", "", "", "", "", "",
      "bopf",
      "ldquo",
      "", "", "",
      "leftthreetimes",
      "",
      "zcy",
      "",
      "ocy",
      "", "",
      "topbot",
      "", "",
      "wscr",
      "doteq",
      "", "", "", "",
      "upsih",
      "", "",
      "PrecedesSlantEqual",
      "csup",
      "",
      "plusdu",
      "", "", "", "",
      "notinE",
      "", "", "", "",
      "aopf",
      "", "", "",
      "acd",
      "", "", "", "",
      "amp",
      "hyphen",
      "ropar",
      "And",
      "ac",
      "image",
      "", "", "",
      "nexist",
      "rtrie",
      "capcap",
      "", "",
      "heartsuit",
      "lmoustache",
      "iquest",
      "", "",
      "ap",
      "grave",
      "",
      "ge",
      "", "", "",
      "CapitalDifferentialD",
      "plustwo",
      "lnE",
      "ncup",
      "", "", "", "", "", "",
      "softcy",
      "", "",
      "QUOT",
      "", "", "",
      "capbrcup",
      "",
      "vDash",
      "", "", "", "",
      "larrb",
      "", "",
      "Not",
      "",
      "LeftVector",
      "", "",
      "Dcy",
      "",
      "pound",
      "", "", "", "",
      "TildeEqual",
      "Nacute",
      "nvrtrie",
      "Nfr",
      "",
      "Breve",
      "", "",
      "boxdr",
      "",
      "Aogon",
      "", "",
      "icy",
      "",
      "Iogon",
      "", "", "", "", "", "", "", "", "",
      "ltrie",
      "", "", "", "",
      "simgE",
      "", "", "", "", "",
      "Dagger",
      "", "", "",
      "sqsub",
      "", "",
      "capand",
      "", "", "", "", "",
      "nles",
      "", "",
      "boxV",
      "boxur",
      "", "", "",
      "COPY",
      "leq",
      "kopf",
      "", "", "",
      "ncy",
      "", "", "", "",
      "int",
      "zeetrf",
      "", "", "",
      "realpart",
      "", "", "",
      "topfork",
      "Acy",
      "", "", "", "",
      "Icy",
      "",
      "nwarrow",
      "lesges",
      "",
      "bfr",
      "rtri",
      "lesseqqgtr",
      "ApplyFunction",
      "", "", "",
      "notin",
      "", "", "", "", "", "", "", "",
      "osol",
      "dharr",
      "",
      "RightUpVectorBar",
      "",
      "gesl",
      "ccirc",
      "Ncaron",
      "", "",
      "nLtv",
      "robrk",
      "Abreve",
      "",
      "reg",
      "nvgt",
      "", "", "",
      "deg",
      "bscr",
      "afr",
      "timesb",
      "intprod",
      "",
      "af",
      "",
      "RightFloor",
      "", "",
      "Rcy",
      "", "", "",
      "Int",
      "",
      "ecirc",
      "", "", "",
      "LeftFloor",
      "", "",
      "coloneq",
      "",
      "ocir",
      "uharr",
      "",
      "LeftArrowBar",
      "",
      "HorizontalLine",
      "",
      "barvee",
      "nsupset",
      "", "", "", "", "",
      "vee",
      "omid",
      "Jcirc",
      "", "",
      "nGg",
      "",
      "Congruent",
      "", "", "",
      "RightDoubleBracket",
      "Wcirc",
      "", "", "", "",
      "nsucc",
      "", "", "", "",
      "apE",
      "", "", "",
      "Star",
      "NotGreater",
      "", "", "", "",
      "lobrk",
      "",
      "lbrksld",
      "", "",
      "Uogon",
      "", "",
      "yen",
      "",
      "lhard",
      "", "", "", "",
      "nsupe",
      "", "", "", "",
      "epsiv",
      "nvrArr",
      "", "", "", "", "", "", "",
      "copy",
      "", "", "",
      "UnderBar",
      "", "", "", "", "", "",
      "Gcirc",
      "vsupne",
      "",
      "NotEqual",
      "", "",
      "NotPrecedesEqual",
      "lbrkslu",
      "bigsqcup",
      "", "", "", "",
      "gel",
      "", "", "",
      "bigstar",
      "",
      "rdsh",
      "lbrke",
      "gtrdot",
      "gE",
      "kfr",
      "dzcy",
      "",
      "lsaquo",
      "nvltrie",
      "TSHcy",
      "ring",
      "zigrarr",
      "rarrhk",
      "", "",
      "lang",
      "",
      "vsupnE",
      "NotLess",
      "", "",
      "NotGreaterEqual",
      "", "", "",
      "NotGreaterFullEqual",
      "", "", "", "",
      "edot",
      "Ocirc",
      "",
      "nearrow",
      "Ubrcy",
      "", "", "", "",
      "awconint",
      "kscr",
      "starf",
      "", "", "", "", "", "", "", "",
      "NestedLessLess",
      "",
      "FilledVerySmallSquare",
      "", "", "", "",
      "rightrightarrows",
      "Proportional",
      "Scy",
      "nwnear",
      "ast",
      "", "", "",
      "Edot",
      "", "", "", "",
      "YUcy",
      "", "",
      "gtquest",
      "",
      "odot",
      "", "", "", "", "", "", "",
      "bigodot",
      "DifferentialD",
      "",
      "NotDoubleVerticalBar",
      "", "",
      "lne",
      "", "",
      "rharul",
      "", "", "",
      "leftharpoondown",
      "", "", "", "", "", "",
      "gtrless",
      "", "", "",
      "Assign",
      "", "", "",
      "Acirc",
      "", "", "", "",
      "operp",
      "", "", "", "", "", "", "",
      "ycy",
      "REG",
      "", "", "", "", "",
      "hcirc",
      "", "", "", "",
      "gtdot",
      "ssetmn",
      "", "", "",
      "lharu",
      "", "", "", "", "",
      "gbreve",
      "",
      "sstarf",
      "", "", "", "", "", "", "", "",
      "nspar",
      "",
      "exponentiale",
      "", "",
      "LeftTee",
      "NotReverseElement",
      "bigotimes",
      "", "", "", "", "",
      "gtreqqless",
      "Exists",
      "leftrightharpoons",
      "UpArrow",
      "",
      "szlig",
      "", "", "", "", "",
      "lagran",
      "varsubsetneq",
      "LeftTeeVector",
      "",
      "sqsubseteq",
      "", "", "", "", "", "", "", "", "",
      "",
      "ClockwiseContourIntegral",
      "", "", "", "",
      "preccurlyeq",
      "", "",
      "nang",
      "",
      "bprime",
      "NotLessEqual",
      "Psi",
      "", "",
      "dstrok",
      "", "",
      "tscy",
      "", "", "", "", "", "",
      "nvlArr",
      "",
      "boxUr",
      "", "", "", "", "", "", "", "", "",
      "",
      "DownLeftVector",
      "", "",
      "map",
      "cwint",
      "", "",
      "rarrsim",
      "omicron",
      "mopf",
      "LessSlantEqual",
      "",
      "inodot",
      "", "",
      "KHcy",
      "",
      "pm",
      "",
      "integers",
      "", "",
      "barwed",
      "",
      "gEl",
      "Idot",
      "",
      "bernou",
      "",
      "ncongdot",
      "", "", "",
      "RightTriangleBar",
      "Poincareplane",
      "", "",
      "dfisht",
      "", "", "",
      "gtcir",
      "TRADE",
      "",
      "macr",
      "Backslash",
      "", "", "", "",
      "OpenCurlyQuote",
      "", "", "", "", "",
      "blacklozenge",
      "", "", "",
      "YIcy",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "",
      "ape",
      "",
      "mid",
      "DiacriticalTilde",
      "bNot",
      "",
      "ufisht",
      "boxh",
      "boxVL",
      "", "",
      "larrsim",
      "", "",
      "RightTriangle",
      "", "", "", "", "",
      "OverParenthesis",
      "", "",
      "LessFullEqual",
      "pitchfork",
      "", "", "", "", "", "",
      "udblac",
      "Omicron",
      "",
      "lesg",
      "eta",
      "lfisht",
      "scnap",
      "",
      "RightTriangleEqual",
      "", "", "", "",
      "Because",
      "", "",
      "acute",
      "", "", "", "",
      "rightleftarrows",
      "", "", "", "", "", "", "", "",
      "there4",
      "", "", "",
      "lparlt",
      "", "",
      "CounterClockwiseContourIntegral",
      "",
      "Eta",
      "", "", "",
      "PlusMinus",
      "", "", "", "",
      "RightArrowBar",
      "", "", "", "", "", "",
      "odblac",
      "", "",
      "nwarhk",
      "", "", "",
      "sqcaps",
      "",
      "iiint",
      "Dstrok",
      "",
      "square",
      "",
      "OpenCurlyDoubleQuote",
      "", "", "",
      "leqq",
      "mapsto",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "",
      "LeftArrow",
      "circledcirc",
      "", "", "",
      "therefore",
      "frown",
      "RightDownVector",
      "sim",
      "boxvh",
      "looparrowright",
      "",
      "Lstrok",
      "", "",
      "notinva",
      "", "",
      "lrm",
      "", "", "", "", "", "",
      "complement",
      "OverBrace",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "OverBracket",
      "", "", "", "", "", "", "",
      "sharp",
      "", "",
      "boxvL",
      "micro",
      "", "", "", "", "", "", "", "",
      "shortmid",
      "circlearrowleft",
      "", "",
      "equivDD",
      "", "", "",
      "Odblac",
      "", "", "",
      "infin",
      "simplus",
      "", "", "",
      "breve",
      "", "",
      "leftarrowtail",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "upuparrows",
      "", "", "", "", "", "", "", "",
      "DJcy",
      "csube",
      "",
      "angrt",
      "boxhU",
      "twoheadleftarrow",
      "angrtvbd",
      "origof",
      "",
      "oslash",
      "gdot",
      "", "", "",
      "kcy",
      "", "", "", "",
      "VeryThinSpace",
      "",
      "vnsub",
      "", "", "", "", "", "", "",
      "LongLeftArrow",
      "", "",
      "NotSucceeds",
      "", "",
      "LJcy",
      "", "", "",
      "shy",
      "", "", "", "",
      "tosa",
      "", "",
      "maltese",
      "",
      "gne",
      "", "", "", "", "", "",
      "bigtriangledown",
      "NotSucceedsTilde",
      "", "",
      "yacy",
      "UpperRightArrow",
      "ange",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "NotSucceedsEqual",
      "",
      "male",
      "", "",
      "NotSucceedsSlantEqual",
      "", "", "", "",
      "seswar",
      "", "",
      "boxuR",
      "", "", "", "", "", "", "", "", "",
      "DownArrow",
      "", "", "",
      "incare",
      "", "", "", "", "", "",
      "UpTeeArrow",
      "", "",
      "shortparallel",
      "SHcy",
      "", "", "",
      "biguplus",
      "", "", "", "", "", "", "", "", "",
      "bigwedge",
      "",
      "rightarrow",
      "", "", "",
      "yicy",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "andv",
      "", "", "",
      "NotLeftTriangleEqual",
      "", "", "",
      "rsqb",
      "",
      "isinsv",
      "", "", "", "",
      "GreaterGreater",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "bigoplus",
      "",
      "ForAll",
      "", "",
      "DownRightVectorBar",
      "", "", "", "", "", "", "", "",
      "nsubset",
      "", "",
      "circleddash",
      "eqcolon",
      "",
      "rbrack",
      "", "", "", "", "", "", "", "",
      "NotHumpEqual",
      "", "", "", "",
      "leftrightarrows",
      "hslash",
      "",
      "trisb",
      "", "", "", "", "", "", "",
      "boxUL",
      "",
      "phone",
      "", "",
      "GreaterFullEqual",
      "", "",
      "horbar",
      "", "", "", "", "", "", "",
      "lsqb",
      "sqsupseteq",
      "", "",
      "precneqq",
      "boxDR",
      "nsube",
      "", "",
      "boxvH",
      "", "",
      "Hstrok",
      "", "", "",
      "LeftArrowRightArrow",
      "",
      "egs",
      "",
      "RightDownTeeVector",
      "", "",
      "NestedGreaterGreater",
      "", "", "", "", "", "",
      "rhov",
      "",
      "vsubne",
      "",
      "boxHU",
      "", "",
      "Verbar",
      "",
      "lbrack",
      "fork",
      "", "", "", "",
      "scsim",
      "",
      "itilde",
      "", "",
      "Therefore",
      "",
      "weierp",
      "", "",
      "ntriangleright",
      "", "", "", "",
      "eqsim",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "nabla",
      "", "", "", "", "",
      "bne",
      "bnot",
      "",
      "upsilon",
      "boxH",
      "", "", "", "", "", "", "", "", "",
      "xopf",
      "", "",
      "hamilt",
      "ntilde",
      "jfr",
      "", "",
      "sdotb",
      "", "", "", "",
      "rangle",
      "", "", "", "", "", "", "",
      "gtrarr",
      "", "", "", "",
      "Lambda",
      "", "", "", "", "", "", "", "", "",
      "",
      "cupdot",
      "", "", "",
      "ntriangleleft",
      "", "",
      "wedgeq",
      "", "",
      "geqq",
      "nsubE",
      "ccupssm",
      "",
      "LessGreater",
      "subdot",
      "OElig",
      "", "", "", "", "", "",
      "xmap",
      "zwj",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "",
      "triangle",
      "lurdshar",
      "",
      "iota",
      "", "", "", "", "", "", "", "", "",
      "",
      "triangleleft",
      "", "", "", "", "", "",
      "SquareSuperset",
      "", "", "", "",
      "verbar",
      "lgE",
      "", "", "", "", "", "", "", "", "",
      "",
      "leftleftarrows",
      "", "", "", "", "", "",
      "Lleftarrow",
      "", "", "", "",
      "nleftrightarrow",
      "",
      "supe",
      "", "", "", "", "", "", "",
      "uhblk",
      "",
      "UpArrowDownArrow",
      "", "", "",
      "RightArrow",
      "",
      "cupor",
      "GreaterTilde",
      "",
      "plussim",
      "LeftTeeArrow",
      "", "",
      "SmallCircle",
      "Element",
      "", "", "",
      "nleftarrow",
      "",
      "between",
      "", "", "", "", "", "", "", "", "",
      "",
      "chi",
      "leftarrow",
      "", "",
      "profline",
      "", "", "", "", "", "", "",
      "ang",
      "", "", "",
      "boxUR",
      "", "", "", "", "",
      "odsold",
      "", "",
      "DownRightTeeVector",
      "", "",
      "xfr",
      "NotCupCap",
      "", "", "", "",
      "subE",
      "", "", "", "",
      "delta",
      "", "", "", "",
      "PartialD",
      "", "", "", "",
      "Cup",
      "",
      "NJcy",
      "", "", "", "", "",
      "nLeftrightarrow",
      "", "", "", "", "",
      "thinsp",
      "", "", "",
      "blank",
      "", "", "",
      "rceil",
      "", "", "",
      "Beta",
      "", "",
      "lowbar",
      "euro",
      "",
      "gimel",
      "",
      "realine",
      "",
      "Zeta",
      "cupcup",
      "",
      "div",
      "ngt",
      "", "", "", "", "", "", "",
      "xi",
      "", "", "",
      "nlsim",
      "", "", "", "",
      "supsup",
      "", "", "", "",
      "subsup",
      "", "",
      "uuml",
      "", "", "", "", "", "",
      "lcub",
      "mnplus",
      "",
      "euml",
      "", "", "",
      "VerticalSeparator",
      "curlyeqsucc",
      "",
      "urtri",
      "", "", "",
      "NegativeVeryThinSpace",
      "UnionPlus",
      "", "",
      "curlyeqprec",
      "", "", "", "", "", "",
      "curlyvee",
      "nsupseteqq",
      "",
      "imagline",
      "",
      "lceil",
      "",
      "curlywedge",
      "", "",
      "blk34",
      "",
      "orv",
      "Euml",
      "", "",
      "luruhar",
      "",
      "forall",
      "", "",
      "commat",
      "",
      "ouml",
      "", "", "", "",
      "midast",
      "", "",
      "Mu",
      "", "", "",
      "phiv",
      "", "", "", "",
      "boxplus",
      "", "", "",
      "subne",
      "jmath",
      "nrtrie",
      "",
      "lsh",
      "ldca",
      "", "", "", "", "", "", "", "", "",
      "wreath",
      "", "", "",
      "boxdl",
      "", "",
      "iinfin",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "",
      "triangledown",
      "", "", "", "", "", "",
      "circledast",
      "", "", "",
      "suphsol",
      "", "", "", "", "", "", "", "", "",
      "nltrie",
      "",
      "boxVl",
      "", "", "", "", "", "",
      "parallel",
      "bottom",
      "", "", "", "",
      "isinv",
      "",
      "vzigzag",
      "", "", "", "",
      "Ouml",
      "", "", "", "", "", "", "",
      "rcedil",
      "", "", "", "", "",
      "leftrightarrow",
      "iuml",
      "",
      "vrtri",
      "tcedil",
      "", "", "", "",
      "Gammad",
      "", "", "", "",
      "rthree",
      "", "", "",
      "nesim",
      "", "", "", "", "",
      "ccedil",
      "", "", "", "", "",
      "Ntilde",
      "", "", "",
      "NotHumpDownHump",
      "", "", "",
      "NotElement",
      "", "", "", "", "", "",
      "Gg",
      "", "",
      "backsimeq",
      "", "", "", "",
      "prime",
      "bsolb",
      "Sup",
      "", "",
      "vltri",
      "ruluhar",
      "", "", "", "", "",
      "wedbar",
      "", "",
      "nsubseteq",
      "", "", "", "",
      "Downarrow",
      "", "",
      "glj",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "",
      "NegativeThinSpace",
      "sigmaf",
      "",
      "circledS",
      "",
      "Fouriertrf",
      "",
      "notnivc",
      "", "",
      "Supset",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "",
      "angsph",
      "", "", "", "", "",
      "nltri",
      "block",
      "Longrightarrow",
      "", "", "",
      "SquareIntersection",
      "", "", "", "", "", "", "",
      "djcy",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "Gcedil",
      "", "",
      "atilde",
      "", "", "", "", "", "", "",
      "Superset",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "triangleq",
      "", "", "", "", "", "", "",
      "checkmark",
      "", "",
      "xcup",
      "", "",
      "ntrianglelefteq",
      "",
      "rtriltri",
      "cuesc",
      "",
      "nequiv",
      "",
      "kappa",
      "", "", "", "", "", "", "",
      "vellip",
      "", "", "", "", "",
      "veebar",
      "", "", "", "", "", "", "", "", "",
      "",
      "nge",
      "", "", "",
      "Succeeds",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "trianglelefteq",
      "LeftTriangleBar",
      "nges",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "female",
      "", "", "", "", "", "",
      "lsime",
      "", "", "", "",
      "succeq",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "supsetneq",
      "", "", "", "",
      "subsetneq",
      "", "", "", "",
      "apacir",
      "",
      "LeftTriangle",
      "", "",
      "eth",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "",
      "Mellintrf",
      "", "", "", "", "", "", "",
      "npolint",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "boxtimes",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "yuml",
      "", "", "", "", "", "",
      "bbrk",
      "", "", "", "",
      "jcirc",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "subrarr",
      "", "", "", "", "", "", "", "", "",
      "supdsub",
      "",
      "curvearrowleft",
      "", "", "", "", "", "", "", "",
      "divideontimes",
      "", "",
      "precnapprox",
      "gammad",
      "", "", "",
      "gneq",
      "gneqq",
      "",
      "omega",
      "",
      "cupcap",
      "", "", "",
      "ReverseElement",
      "", "", "", "", "", "", "", "", "",
      "",
      "alpha",
      "", "", "", "",
      "updownarrow",
      "", "", "", "",
      "gvertneqq",
      "",
      "tritime",
      "diam",
      "", "", "",
      "cupbrcap",
      "", "", "", "", "", "", "", "",
      "suplarr",
      "", "",
      "alefsym",
      "",
      "ffllig",
      "", "", "", "", "", "", "", "",
      "ijlig",
      "", "", "", "", "", "", "", "",
      "dbkarow",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "backcong",
      "",
      "Scedil",
      "",
      "ordm",
      "", "",
      "nbumpe",
      "bigcirc",
      "", "", "", "", "", "", "", "", "",
      "",
      "Omega",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "",
      "ShortUpArrow",
      "bumpe",
      "UnderBracket",
      "", "", "", "", "", "", "", "",
      "numsp",
      "", "", "", "", "",
      "ShortLeftArrow",
      "", "", "",
      "xcirc",
      "", "",
      "Equal",
      "", "", "",
      "rtimes",
      "",
      "laemptyv",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "",
      "ThinSpace",
      "", "",
      "UpEquilibrium",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "angmsdad",
      "", "", "", "", "", "", "", "", "",
      "supsub",
      "",
      "GreaterSlantEqual",
      "", "",
      "NotRightTriangleBar",
      "", "", "", "",
      "angmsdaf",
      "", "", "", "",
      "auml",
      "", "", "", "", "",
      "ltimes",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "angmsdac",
      "nsubseteqq",
      "",
      "rAtail",
      "", "",
      "kgreen",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "",
      "NotRightTriangle",
      "", "", "", "", "", "", "", "",
      "suphsub",
      "", "", "", "", "", "",
      "sung",
      "", "", "", "", "", "",
      "bepsi",
      "",
      "nRightarrow",
      "", "",
      "bullet",
      "",
      "cularr",
      "", "", "", "", "", "", "",
      "angmsdae",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "cularrp",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "",
      "asymp",
      "bull",
      "", "",
      "Otimes",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "bowtie",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "",
      "subseteqq",
      "",
      "parsim",
      "", "", "", "", "",
      "ShortRightArrow",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "",
      "Sub",
      "", "",
      "Updownarrow",
      "phmmat",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "",
      "midcir",
      "", "", "", "",
      "prnsim",
      "",
      "SuchThat",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "ugrave",
      "", "", "", "", "", "", "", "", "",
      "",
      "notniva",
      "", "", "", "", "", "", "",
      "sigma",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "",
      "ThickSpace",
      "", "", "", "", "", "", "", "",
      "succneqq",
      "Egrave",
      "",
      "UpDownArrow",
      "", "", "", "", "", "", "",
      "ograve",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "NotTildeTilde",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "",
      "dotminus",
      "", "",
      "supplus",
      "", "", "",
      "ngeqslant",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "",
      "igrave",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "precnsim",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "DoubleRightTee",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "InvisibleTimes",
      "",
      "ShortDownArrow",
      "", "",
      "Igrave",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "",
      "ffilig",
      "", "", "", "", "",
      "hookrightarrow",
      "", "",
      "submult",
      "", "",
      "RuleDelayed",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "",
      "DoubleLeftRightArrow",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "HumpEqual",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "boxbox",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "varsigma",
      "yucy",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "",
      "Ugrave",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "",
      "asympeq",
      "", "", "", "", "", "", "", "", "",
      "ngeq",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "",
      "setminus",
      "straightphi",
      "", "", "", "", "", "", "", "", "",
      "",
      "zwnj",
      "", "", "", "", "", "", "",
      "thkap",
      "",
      "intlarhk",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "",
      "hookleftarrow",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "",
      "lsim",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "",
      "DoubleRightArrow",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "agrave",
      "", "", "", "",
      "angmsdag",
      "", "", "", "", "",
      "Jukcy",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "nshortparallel",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "boxminus",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "",
      "DoubleLongRightArrow",
      "", "", "",
      "DoubleLongLeftRightArrow",
      "", "",
      "ReverseEquilibrium",
      "", "", "", "", "",
      "divonx",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "iukcy",
      "",
      "xuplus",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "doublebarwedge",
      "curarrm",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "",
      "succnapprox",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "",
      "gtrsim",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "quatint",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "brvbar",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "mcomma",
      "", "", "", "", "", "", "", "", "",
      "",
      "gsim",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "ReverseUpEquilibrium",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "",
      "angmsdaa",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "",
      "xdtri",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "bsim",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "",
      "thicksim",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "",
      "mumap",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "",
      "lnapprox",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "precapprox"
    };

  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      unsigned int key = hash (str, len);

      if (key <= MAX_HASH_VALUE)
        {
          const char *s = wordlist[key];

          if (*str == *s && !strcmp (str + 1, s + 1))
            return s;
        }
    }
  return 0;
}

#include <string_view>

bool found(std::string_view x)
{
  return Perfect_Hash::in_word_set(x.data(),x.size());
}
